#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ${FLOOD_AUTH} == true ]]; then
    FLOOD_OPTION_AUTH=default && export FLOOD_OPTION_AUTH
    echo "qBittorrent is running on \"http://127.0.0.1:${WEBUI_PORTS%%/*}\" for Flood configuration."
else
    FLOOD_OPTION_AUTH=none && export FLOOD_OPTION_AUTH
fi

# shellcheck disable=SC2086
exec s6-setuidgid hotio "${APP_DIR}/flood" --rundir "${CONFIG_DIR}/flood" --host 0.0.0.0 --port "$(grep -Eo '[0-9]*' <<< ${WEBUI_PORTS} | tail -1)" --qburl "http://127.0.0.1:${WEBUI_PORTS%%/*}" --qbuser "dummy" --qbpass "dummy" ${FLOOD_ARGS}
